### ISSUE TITLE
Metasploit Fails to Install

### ISSUE THREAD

**Issue by rcantec** [fireeye/commando-vm#28]
**Metasploit Fails to install**
Directory empty.

**To Reproduce**
1.  Set-ExecutionPolicy Unrestricted
2. .\install.ps1

Error 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - Metasploit - Metasploit not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

**Version**
 - OS: Windows 10 x64

**Comment by AndrzejRPiotrowski** [comment]
Metasploit works ok 
Version
OS: Windows 10 x64 Home Edition

**Comment by machGhosTine** [comment]
I had issues with certain packages not installing. use 'choco install metasploit' from cmd/ps prompt.

**Comment by rcantec** [comment]
> I had issues with certain packages not installing. use 'choco install metasploit' from cmd/ps prompt.

**Comment by rcantec** [comment]
specifying --pre also makes no difference

**Comment by rcantec** [comment]
_ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
Installing the following packages:
metasploit
By installing you accept licenses for the packages.
metasploit not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "C:\ProgramData\Boxstarter\BuildPackages;https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - metasploit - metasploit not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""

**Comment by machGhosTine** [comment]
I don't know if this is still an issue for you, but I am going to be flashing commando on my other laptop later tonight, and I'll let you know if I run into any metasploit install issues and how to remedy them.

**Comment by rcantec** [comment]
Ok sounds good, I ended up deleting commando for the time being, hopefully the install issues get resolved

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by day1player** [comment]
@rcantec the issues should be resolved now. Closing this issue, please open another if you decide to install again and have other issues.

**Comment by rcantec** [comment]
Yes latest version seems to be working great thank you!

**Comment by zeeshan1991k** [comment]
proxycap and metasploit fails to install. How to rectify it?

**Comment by cybersecdo** [comment]
hello 
i have the same issue , i just installed the commando-vm in my windows 10
in the tools area i have tools but metasploit missing and nmap ....i try to choco install metasploit i get this:


C:\Users\cyber\Desktop
λ choco install metasploit
Chocolatey v0.10.13
Installing the following packages:
metasploit
By installing you accept licenses for the packages.
metasploit not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - metasploit - metasploit not installed. The package was not found with the source(s) listed.

 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

i have problems whit nmap ...i install whit the choco install nmap but i try to open in cmd and not found maybe i have to change the path but i dont know how to do
C:\Users\cyber\Desktop
λ choco install nmap
Chocolatey v0.10.13
Installing the following packages:
nmap
By installing you accept licenses for the packages.
nmap v7.70 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

I RUN NMAP AND I GET THIS OUTPUT I DONT UNDERSTAND???
C:\Users\cyber\Desktop
λ nmap --help
Cannot find file at 'c:\program files (x86)\nmap\nmap.exe' (c:\program files (x86)\nmap\nmap.exe). This usually indicates a missing or moved file.

CAN YOU HELP ME PLEASE ????
THANK YOU SO MUCH!

**Comment by C1S0** [comment]
This issue is still happening on the latest as of today May 9.

λ choco install metasploit
Chocolatey v0.10.13
Installing the following packages:
metasploit
By installing you accept licenses for the packages.
metasploit not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

λ choco info metasploit
Chocolatey v0.10.13
0 packages found.

**Comment by n3tl0kr** [comment]
Seeing similar issues with:

Failed to install dnspy.flare
Failed to install proxycap.fireeye
Failed to install fiddler.fireeye
Failed to install notepadplusplus
Failed to install metasploit.flare
Failed to install Elite.fireeye
Failed to install covenant.fireeye
Failed to install wfuzz.fireeye
Failed to install openvpn.fireeye

**Comment by WayneJLee** [comment]
Metasploit package isn't found using Chocolatey when using

`choco install metasploit
`

Running `choco install metasploit.flare`  works but there's a 404 error from metasploit's site.

> ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.31%2B20190623152611-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
 See log for details.

I have the utmost respect for what you guys are doing but the current installation method has a lot of dependencies that are out of your control. Hope you guys are able to find a long term fix to this problem because I think CommandoVM could be a great alternative to Kali.

**Comment by WayneJLee** [comment]
Metasploit package isn't found using Chocolatey when using

choco install metasploit

Running choco install metasploit.flare works but returns a 404 error from metasploit's site.

ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://windows.metasploit.com/metasploit-framework-5.0.31%2B20190623152611-1rapid7-1-x64.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of metasploit.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\metasploit.flare\tools\chocolateyInstall.ps1'.
See log for details.

I have the utmost respect for what you guys are doing but the current installation method has an issue with dependencies. Hope you guys are able to find a long term fix to this problem because I think CommandoVM could be a great alternative to Kali.

**Comment by djeronimo** [comment]
I am having the same issue as @WayneJLee 
Is there a work around?

**Comment by day1player** [comment]
@djeronimo for now the only way is to manually install the package from metasploit.com. Since they are always updating their build the link is always breaking. It takes some work for us to keep up with it, but we will have a fix out soon.

**Comment by dandymike** [comment]
can you not link the package to the below link instead? Just a suggestion...
https://windows.metasploit.com/metasploitframework-latest.msi

**Comment by day1player** [comment]
@dandymike we could but then we would have to forgo the hash checking of the binary during the install which is no bueno.

**Comment by dandymike** [comment]
@day1player I didn’t think about that, I’ll go back in my hole and wait for the sources list to be updated :)
